// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.ndnu.capstone.domain;

import edu.ndnu.capstone.domain.EmergencyType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmergencyType_Roo_Configurable {
    
    declare @type: EmergencyType: @Configurable;
    
}
