// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.ndnu.capstone.model;

import edu.ndnu.capstone.domain.EmergencyStatus;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmergencyStatus_Roo_Configurable {
    
    declare @type: EmergencyStatus: @Configurable;
    
}
