// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.ndnu.capstone.domain;

import edu.ndnu.capstone.domain.EmergencyStatus;
import edu.ndnu.capstone.domain.EmergencyStatusDataOnDemand;
import edu.ndnu.capstone.domain.EmergencyStatusService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EmergencyStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmergencyStatusDataOnDemand: @Component;
    
    private Random EmergencyStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<EmergencyStatus> EmergencyStatusDataOnDemand.data;
    
    @Autowired
    EmergencyStatusService EmergencyStatusDataOnDemand.emergencyStatusService;
    
    public EmergencyStatus EmergencyStatusDataOnDemand.getNewTransientEmergencyStatus(int index) {
        EmergencyStatus obj = new EmergencyStatus();
        setName(obj, index);
        return obj;
    }
    
    public void EmergencyStatusDataOnDemand.setName(EmergencyStatus obj, int index) {
        String name = "name_" + index;
        if (name.length() > 256) {
            name = name.substring(0, 256);
        }
        obj.setName(name);
    }
    
    public EmergencyStatus EmergencyStatusDataOnDemand.getSpecificEmergencyStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EmergencyStatus obj = data.get(index);
        Integer id = obj.getId();
        return emergencyStatusService.findEmergencyStatus(id);
    }
    
    public EmergencyStatus EmergencyStatusDataOnDemand.getRandomEmergencyStatus() {
        init();
        EmergencyStatus obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return emergencyStatusService.findEmergencyStatus(id);
    }
    
    public boolean EmergencyStatusDataOnDemand.modifyEmergencyStatus(EmergencyStatus obj) {
        return false;
    }
    
    public void EmergencyStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = emergencyStatusService.findEmergencyStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EmergencyStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EmergencyStatus>();
        for (int i = 0; i < 10; i++) {
            EmergencyStatus obj = getNewTransientEmergencyStatus(i);
            try {
                emergencyStatusService.saveEmergencyStatus(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
