// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.ndnu.capstone.domain;

import edu.ndnu.capstone.domain.EmergencyType;
import edu.ndnu.capstone.domain.EmergencyTypeDataOnDemand;
import edu.ndnu.capstone.domain.EmergencyTypeService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EmergencyTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmergencyTypeDataOnDemand: @Component;
    
    private Random EmergencyTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<EmergencyType> EmergencyTypeDataOnDemand.data;
    
    @Autowired
    EmergencyTypeService EmergencyTypeDataOnDemand.emergencyTypeService;
    
    public EmergencyType EmergencyTypeDataOnDemand.getNewTransientEmergencyType(int index) {
        EmergencyType obj = new EmergencyType();
        setName(obj, index);
        return obj;
    }
    
    public void EmergencyTypeDataOnDemand.setName(EmergencyType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 256) {
            name = name.substring(0, 256);
        }
        obj.setName(name);
    }
    
    public EmergencyType EmergencyTypeDataOnDemand.getSpecificEmergencyType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EmergencyType obj = data.get(index);
        Integer id = obj.getId();
        return emergencyTypeService.findEmergencyType(id);
    }
    
    public EmergencyType EmergencyTypeDataOnDemand.getRandomEmergencyType() {
        init();
        EmergencyType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return emergencyTypeService.findEmergencyType(id);
    }
    
    public boolean EmergencyTypeDataOnDemand.modifyEmergencyType(EmergencyType obj) {
        return false;
    }
    
    public void EmergencyTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = emergencyTypeService.findEmergencyTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EmergencyType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EmergencyType>();
        for (int i = 0; i < 10; i++) {
            EmergencyType obj = getNewTransientEmergencyType(i);
            try {
                emergencyTypeService.saveEmergencyType(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
